services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    restart: always
    command:
      - start-dev
      - --import-realm
    environment:
      KC_HTTP_PORT: 8080
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: DEBUG
    ports:
      - 8080:8080
    volumes:
      - ./playground-realm.json:/opt/keycloak/data/import/playground-realm.json
      - ./login.ftl:/opt/keycloak/themes/vinpay/login/login.ftl
      - ./target/recaptcha-login.jar:/opt/keycloak/providers/recaptcha-login.jar
